SITE_NAME = 'Unnamed'
SITE_TAGLINE = 'Unttitle'
SHOW_REGISTRATION_MENU = False
YOUTUBE_LINK = None
ACTIVE_MENU = None
ADSENSE_INAPP_ARTICLE_CODE = None
ADSENSE_INFEED_CODE = None
ADSENSE_PAGELEVEL_CODE = None
