SITE_NAME = 'Unnamed'
SITE_TAGLINE = 'Unttitle'
SHOW_REGISTRATION_MENU = True
YOUTUBE_LINK = None
ACTIVE_MENU = None
DESCRIPTION = None

#ALL ADSENSE CODE
ADSENSE_INAPP_ARTICLE_CODE = None
ADSENSE_INFEED_CODE = None
ADSENSE_PAGELEVEL_CODE = None
ADSENSE_HEADER = None
ADSENSE_FOOTER = None

ADSENSE_SKYSCRAPER = []