"""Add child click bait

Revision ID: 062a956982a1
Revises: 5d418e1b58ba
Create Date: 2017-12-12 10:01:48.224517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062a956982a1'
down_revision = '5d418e1b58ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_clickbait',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('stamp', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='fx_child_click'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clickbait_pages',
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('master_clickbait_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_clickbait_id'], ['master_clickbait.id'], name='fx_child_1'),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], name='fx_child_2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clickbait_pages')
    op.drop_table('master_clickbait')
    # ### end Alembic commands ###
