"""add password

Revision ID: 13734072a120
Revises: 31cd46128048
Create Date: 2017-12-14 02:23:56.196327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13734072a120'
down_revision = '31cd46128048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('is_protected', sa.Boolean(), nullable=True))
    op.add_column('page', sa.Column('password', sa.String(length=255), nullable=True))
    op.execute("Update Page set is_protected=False, password=null")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'password')
    op.drop_column('page', 'is_protected')
    # ### end Alembic commands ###
