"""Add youtube

Revision ID: 31cd46128048
Revises: 907c2f1821eb
Create Date: 2017-12-13 01:10:14.830400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31cd46128048'
down_revision = '907c2f1821eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('feature_youtube_embed_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'feature_youtube_embed_code')
    # ### end Alembic commands ###
