"""menu

Revision ID: 3c7a32f19f52
Revises: 4fe904b1fa08
Create Date: 2017-11-24 23:25:20.217168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7a32f19f52'
down_revision = '4fe904b1fa08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(u'page_unique_title', 'page', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'page_unique_title', 'page', ['title'])
    op.drop_table('menu')
    # ### end Alembic commands ###
