"""Add username

Revision ID: 5d418e1b58ba
Revises: b99e8542f5da
Create Date: 2017-12-11 23:14:16.422451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d418e1b58ba'
down_revision = 'b99e8542f5da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'], name='uniq_user') #TODO name is missing
    op.execute('update "user" set username=email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
