"""External featuer url

Revision ID: 907c2f1821eb
Revises: cf5828483bde
Create Date: 2017-12-12 22:42:40.084469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907c2f1821eb'
down_revision = 'cf5828483bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('feature_image_external_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'feature_image_external_url')
    # ### end Alembic commands ###
