"""Add prev next page

Revision ID: b0b00eb4a779
Revises: 5d418e1b58ba
Create Date: 2017-12-12 10:34:46.858159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b00eb4a779'
down_revision = '5d418e1b58ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('next_page_id', sa.Integer(), nullable=True))
    op.add_column('page', sa.Column('prev_page_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fx_page_next', 'page', 'page', ['next_page_id'], ['id'])
    op.create_foreign_key('fx_page_prev', 'page', 'page', ['prev_page_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fx_page_prev', 'page', type_='foreignkey')
    op.drop_constraint('fx_page_next', 'page', type_='foreignkey')
    op.drop_column('page', 'prev_page_id')
    op.drop_column('page', 'next_page_id')
    # ### end Alembic commands ###
